public class DifferenceConsAndMethod {
    
    //Constructor is very much similar to a method with the only difference that construction gets invoked the moment class gets 
    //initialised. Where as method gets invoked when a user clicks on a button or link.
    
    public DifferenceConsAndMethod(){
        //This is a constructor
        System.debug('This is a constructor');
    }
    
    public void save(){
        System.debug('This is save method');
    }
    
}